
name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * 0' # Runs every week
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC7SUEMdep7lCz1bXeWCOOtg,https://www.youtube.com/feeds/videos.xml?channel_id=UC6EEGk0N9sad84YU_uXTVMw"